# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 199535b3eaceb02b9cad57364d9754da094d3ed51cdc65679c67fa2656bc611b18a05a9158a1e6750460aa4d7c4d095e420e5abf53c54c561801951319505320

test:
  secret_key_base: bf8b14fa31d1a310d1a57d81b69a7ae7be06786a2d7677f06e59ee2a0fe7a146d752f207fcb157bac33b871ec6817a2c63630eb2d84846a7e4ee85bf2a032bf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
